### ISSUE TITLE
AdGuard dns bêta French list

### ISSUE THREAD

**Issue by tupac55** [AdguardTeam/HostlistsRegistry#16]
It would be great to have AdGuard French list in the custom host list for the new AdGuard beta dns

**Comment by DandelionSprout** [comment]
If I understand your question correctly, you could propose to https://github.com/AdguardTeam/AdGuardSDNSFilter/issues to add `https://easylist-downloads.adblockplus.org/liste_fr.txt` to https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/configuration.json, the latter of which currently only has those French entries that AdGuard themselves added to AdGuard French Filter, and not those that AdGuard French Filter borrows from "Liste FR".

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/HostlistsRegistry/issues/55

**Comment by ameshkov** [comment]
Unfortunately, Liste FR is not a DNS-level blocklist and adding it to AdGuard DNS would cause more problems than solve issues.

If @smed79 at some point decides to split ad servers from other rules, we would be happy to add Liste FR to AdGuard DNS.

**Comment by DandelionSprout** [comment]
One workaround, albeit one that would take quite some time to add to AdGuard Beta DNS (but would be highly feasible in AdGuard Home), would be to use https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AdGuard%20Home%20Compilation%20List/AdGuardHomeCompilationList.txt alongside (or instead of) AdGuard DNS Filter, as the former appears to have more than 10,000 entries from Liste FR.

However, adding new entries to the list is a meticulous process that would take more than half an hour, so I hope I have time to do so this morning.

**Comment by ameshkov** [comment]
We could probably even automate inclusion of the hosts from Liste FR to AdGuard DNS filter, but the point is that without the author manually checking the process there'll be a higher risk of false-positives.
