### ISSUE TITLE
Add Phishing Army

### ISSUE THREAD

**Issue by hg1978** [AdguardTeam/HostlistsRegistry#178]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Phishing Army Extended Blocklist

### Blocklist category

Malware&phishing blocking

### Homepage

https://phishing.army/download/phishing_army_blocklist_extended.txt

### Explanation

Please add the phishing army list instead of the https://gitlab.com/malware-filter/phishing-filter list. That is the official one.

**Comment by Alex-302** [comment]
Why "instead"?

**Comment by Alex-302** [comment]
Checked 10 random domains - all dead.

**Comment by Sergey-Lyapin** [comment]
Regarding the requirements:

`The blocklist should have a place for receiving user complaints and holding discussions, such as a repository on github.com, or a public website/forum.`

Is there such a place?

```
- The blocklist should be relatively popular, meaning:
  - if there is a repository on GitHub, the number of stars should be at least 50.
  - if there is no repository on GitHub, the number of reported issues and discussions should be at least 10 per month.
  - the blocklist should be actively supported for at least 6 months.
- The blocklist should be regularly updated with at least 10 updates per month.
```

How often is the filter updated? I couldn't find any information about it.

**Comment by drego85** [comment]
Thank you @hagezi for the ping, Thank you @hg1978 for the proposal.

I try to explain the project and answer questions.

Phishing Army was born in 2018, because for work I analyze and counter phishing for several European banks. So I thought I would create something useful for the community.

There is an [official website](https://phishing.army/) where I explain several features of the lists, but the source code is also public here on [GitHub](https://github.com/drego85/PhishingArmyCore/).

The list is updated every 6 hours and is currently used by over 400 thousand unique users (4 million monthly downloads). You can find an introduction and other stats on my [personal blog](https://www.andreadraghetti.it/phishing-army-the-blocklist-to-block-phishing/).

I'm active in keeping the list up-to-date and without false positives, I usually respond in the NextDNS repository (it is included in their service since 2018) or even in the list that @hagezi maintains. In addition to emails I receive weekly.

For any clarification, please write to me ;)

PS
@Alex-302  I'm glad you found 10 unreachable domains, because some abuse team works well and shuts down phishing sites!

**Comment by Alex-302** [comment]
> https://phishing.army/download/phishing_army_blocklist_extended.txt
> https://gitlab.com/malware-filter/phishing-filter

I see only 26k identical domains of more than 150k. 
Maybe better to add as a new filter.

**Comment by Sergey-Lyapin** [comment]
Added.
