### ISSUE TITLE
Add missing HaGeZi Blocklists

### ISSUE THREAD

**Issue by brokoler** [AdguardTeam/HostlistsRegistry#335]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

HaGeZi Pro/Pro++/Ultimate

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking

### Homepage

https://github.com/hagezi/dns-blocklists

### Explanation

Hello,

I recently switched to adguard-dns.io and I'm missing blocklists from HaGeZi that I use at home already with Adguard Home.
Right now only HaGeZi Normal is added to adguard-dns.io, for my personal Use Case I'm not fine with any list below Ultimate.
Please consider to also add following Lists:

HaGeZi Multi PRO (Adguard version):
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/pro.txt

HaGeZi Multi PRO++ (Adguard version):
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.txt

HaGeZi Multi Ultimate (Adguard version):
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/ultimate.txt

**Comment by hagezi** [comment]
Thanks @brokoler 

@ameshkov @Alex-302 @Sergey-Lyapin 

I have had a few enquiries over the last 2 weeks regarding the inclusion of the Pro, Pro++ and Ultimate in AdguardDNS. The reason was that people wanted to switch from another service that provides the lists.

Including the Pro should not be a problem as it is one of the balanced lists. Compared to the Multi, a few more trackers are blocked, including the Amazon "fls" and unagi" trackers and others, in addition to a few other extensions.
It is on the borderline of aggressive lists. In my view, this is an enrichment for AdGuardDNS.

For the more aggressive lists, such as Pro++ and Ultimate, a category should be created that makes it clear that these are not simply lists that you "select" if you don't know what you are doing.
Aggressive lists are completely missing in AdGuardDNS. You should change that.

Maybe you could discuss this in the team.

Thanks,
Gerd

**Comment by Alex-302** [comment]
Maybe Normal can be replaced by Pro?

**Comment by hagezi** [comment]
> Maybe Normal can be replaced by Pro?

That's what I meant, but I didn't say it. So yes, you could. ;)

**Comment by brokoler** [comment]
@Alex-302
Could you give a time frame when more HaGeZi Blocklists will be added?
The missing HaGeZi Ultimate blocklist the one thing keeping me away from Adguard DNS yet ;)

**Comment by ameshkov** [comment]
Let's add Pro and Ultimate as a separate options to dev environment, and see how it goes there first.

**Comment by Alex-302** [comment]
@Sergey-Lyapin Please take a look.

**Comment by fynks** [comment]
Have this been accepted because i could not see these lists in production yet

**Comment by hagezi** [comment]
If you add the Ultimate, then please also add the Pro++. Because, the users who don't find the Pro aggressive enough use the Pro++ and they find the Ultimate too aggressive. These are my experiences.

I have built the other versions around the Pro++. The Pro++ was and is the perfect blocklist for me.

So, from my point of view, the Pro (balanced), Pro++(balanced aggressive) and the Ultimate (aggressive) should be added.

Thanks,
Gerd

**Comment by Alex-302** [comment]
Three filters with a similar name may confuse the user. What about `Pro++` and `Ultimate`? Or their difference can be described in the descriptions briefly.

**Comment by Alex-302** [comment]
Both `Multi ULTIMATE` and `Multi PRO++` are agressive and for experienced users. I think it is ok to add them without `Multi PRO++` - for all, and for experienced. But I don't have statistisc about problems, reortad by users.

**Comment by brokoler** [comment]
@Alex-302
This is a very subjective opinion.

For myself I know how to whitelist if a false positive is blocked, also I would like to add that I'm using HaGeZi Ultimate with Adguard Home since weeks and did not have to whitelist anything.

I myself feel restricted if I can't use more aggressive blocklists and this is why I chose to go with NextDNS for now.
Hopefully you are more open to suggestions in future.

**Comment by hagezi** [comment]
aggressive and aggressive not = aggressive :D

The Pro++ is not obsolete just because the Ultimate is also aggressive. If it were obsolete, I would not offer it. Of the aggressive lists, the Pro++ is the most used. 

*The results of a test against the 10000 [whotracks.me](https://whotracks.me/websites.html) pages. All pages were opened and fully loaded via batch in Edge with privacy features turned off. Cookies were all accepted. *

| **List**     | Total queries | Blocked queries | % blocked | % gap to light |
|-------------:|--------------:|----------------:|----------:|---------------:|
| **Ultimate** | 299646        | 131093          | 43.75     | 12.85          |
| **Pro++**    | 299646        | 119681          | 39.94     | 9.05           |
| **Pro**      | 299646        | 97508           | 32.54     | 1.65           |
| **Normal**   | 299646        | 93258           | 31.12     | 0.23           |
| **Light**    | 299646        | 92576           | 30.90     |                |
| **----**     | 299646        | 67888           | 22.66     | -8.24          |

**Comment by Alex-302** [comment]
@hagezi `Pro++` and `Ultimate` have ~4% differense. Is there really a need to add both?

**Comment by hagezi** [comment]
@Alex-302 

There are 4% or 11412 more blocked requests in a test against 10000 defined websites. For the total blocking performance of a list, this is only a guideline for normal use in the home network with various devices that "phone home".

In my opinion, each list version has its raison d'être. But in the end it is your decision. Personally, I would give the user the freedom of choice.

**Comment by Sergey-Lyapin** [comment]
Added.

**Comment by hagezi** [comment]
Once again, a big thank you to the whole team.
