### ISSUE TITLE
Please add QAnon, Conspiracy, Fakenews and Rasist Blocklist

### ISSUE THREAD

**Issue by nichu42** [AdguardTeam/HostlistsRegistry#34]
Please add QAnon, Conspiracy, Fakenews and Rasist Blocklist:

Project Home:
https://github.com/rimu/no-qanon

Direct link to blocklist in AdBlock format:
https://raw.githubusercontent.com/rimu/no-qanon/master/adblock.txt

**Comment by DandelionSprout** [comment]
Based on the research I did for https://github.com/DandelionSprout/adfilt/blob/master/FalukorvList.txt#L68-L72, the list OP is proposing seems a bit harsh in its blocking and could've at least needed some minor changes.

**Comment by badmojr** [comment]
Murky waters! I'd be careful...

**Comment by nichu42** [comment]
I understand that this is not a list for most users. I take back my request and hope for the possibility to add custom lists.

**Comment by DandelionSprout** [comment]
Adding custom lists to AdGuard Home has been possible since at least 2018: Go to the server dashboard → Filters → DNS blocklists → Add blocklist → Add a custom list.

The correct menu will look something like this: 
![image](https://user-images.githubusercontent.com/22780683/172930652-65bc67c8-b2f7-49f1-b0d1-d2cdafdd2160.png)

**Comment by DandelionSprout** [comment]
Ah. That explains it. I often make the mistake of assuming that reporters on this repo use AdGuard Home, or the DNS mode of AdGuard for Windows/Android.
