### ISSUE TITLE
KADHosts

### ISSUE THREAD

**Issue by antek821** [AdguardTeam/HostlistsRegistry#39]
Could you please add the KADHosts list:
https://raw.githubusercontent.com/FiltersHeroes/KADhosts/master/KADhosts.txt
(homepage: https://github.com/FiltersHeroes/KADhosts)

which is the hosts version of the list:
https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_232_KADPrzekrety

**Comment by DandelionSprout** [comment]
At a surface glance, the list seems considerably better than "Polish filters for Pi hole", so I vote in favour of adding it.

**Comment by ameshkov** [comment]
Sorry for the late reply.

Here's what we need to add it:
1. Title (KADHosts?)
2. Very short list description in English

**Comment by krystian3w** [comment]
IMO possible copy description from FiltersRegistry:

https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_232_KADPrzekrety/metadata.json (is really short).

That is origin source and converted to hosts on own environment.

Also Possible consider join with specific regexes for Pi-Hole (a separate file due to the limitations of pi hole and standard DNS services):

https://github.com/FiltersHeroes/KADhosts/raw/master/KADhole.txt (few manually added to file)

**Comment by antek821** [comment]
The title I think might just be: KADHosts (Or KADHole if you decide to follow the suggestions in the previous message)

Description as @krystian3w  wrote above

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersRegistry/issues/466

https://github.com/AdguardTeam/FiltersRegistry/issues/666

**Comment by ameshkov** [comment]
Both AdGuard DNS and AdGuard Home support regular expressions, but we prefer traditional ad blocking syntax:
https://adguard-dns.io/kb/general/dns-filtering-syntax/#regular-expressions

@krystian3w would it be possible to compile a file with additional regular expressions with the syntax AG products understand?

**Comment by krystian3w** [comment]
I think possible, but I suppose most exists in origin file https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt,
 written for uBo and standard AdGuard extension/apps (strict block wall stylized like anti malware warning).

**Comment by ameshkov** [comment]
Wouldn't it be easier to simply use `https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt` as a source for KADHosts here?
